[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

# Build command - use production schema for PostgreSQL
buildCommand = "npm ci && cp prisma/schema.production.prisma prisma/schema.prisma && npx prisma generate && npm run build"

# Start command - only run migrations if DATABASE_URL is available
startCommand = "if [ -n \"$DATABASE_URL\" ]; then npx prisma migrate deploy; fi && npm start"

# Environment variables will be set in Railway dashboard
[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
